production:
  adapter: mysql
  database: demo_shop
  username: root
  password: xxx
  host: localhost

development:
  adapter: mysql
  database: demo_shop
  username: root
  password: xxx
  host: localhost

test:
  adapter: mysql
  database: demo_shop_test
  username: root
  password: xxx
  host: localhost