production:
  adapter: mysql
  database: avarteq_shop
  username: root
  password: xxx
  host: localhost

development:
  adapter: mysql
  database: avarteq_shop
  username: root
  password: xxx
  host: localhost

test:
  adapter: mysql
  database: avarteq_shop_test
  username: root
  password: xxx
  host: localhost